### PR TITLE
Use composer as root for install

### PR DESCRIPTION
**Pull request by JedMeister**
Work around https://github.com/turnkeylinux/tracker/issues/1960 - by running `composer` as root, rather than using `turnkey-composer`.

### CODE REVIEW

**Comment by OnGle** [comment]
Bizarre, how does this fix the issue?

**Comment by JedMeister** [comment]
Yes it is bizarre! Very bizarre!

Apologies if the issue wasn't clear enough.

In an effort to make the issue clearer, 've updated the bug with this (2nd) paragraph:

> The issue is that it's timing out downloading the flex json file. The install works fine up until that point. Clearly that is a 404 download error, but it occurs consistently when using turnkey-composer. For some very strange and unknown reason, running composer as root (as per [link to this PR]) works fine?!

The issue is worth investigating further, but I'd really like to publish Symfony ASAP.

**Comment by JedMeister** [comment]
Actually, just added a bit more info to the issue:

> Initially I thought it might have been a squid (proxy) problem, but I tried clearing the squid cache and same result. It's reproducible on another TKLDev.

**Review by OnGle — APPROVED** [review]
Well that's weird but lgtm!

**Pull request merged**
